### ISSUE TITLE
使用pygame 多窗口显示多视角摄像头

### ISSUE THREAD

**Issue by zczjx** [zczjx/carla-rpc-bridge#1]
@northbigpanda 
1. 使用pygame 进场多进程编程，创建多个显示窗口
2. 将不同角度获取的摄像头数据显示在不同的pygame窗口里，同屏刷新
3. 代码参考 manual_control.py 和 synchronous_mode.py

**Comment by northbigpanda** [comment]
参考yu分支下面的[
manual_control_multicam.py](https://github.com/zczjx/carla-rpc-bridge/blob/yu/manual_control_multicam.py)
